---
- name: function
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, suresh, Venkatesh"
  tasks:
  - name: undefined varibles
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: Print the names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"