---
- name: function
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, suresh, Venkatesh"
  tasks:
  - name: undefined varibles
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: Print the names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map to list
    vars:
      course: 
        name: Ansible 
        duration: 10 hr 
        trainer: joindevops
    ansible.builtin.debug:
      msg: "course info {{ course | dict2items }}"

  - name: item to dictonary
    vars:
      course:
      - {'key': 'name', 'value': 'Ansible'}
      - {'key': 'duration', 'value': '10 hr'}
      - {'key': 'trainer', 'value': 'joindevops'}
    ansible.builtin.debug:
      msg: "course info {{ course | items2dict }}"

  - name: check ip adress
    vars:
      ip: "300.198.145"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"