---
- name: function
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, suresh, Venkatesh"
  tasks:
  - name: undefined varibles
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: Print the names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map to list
    vars:
      course: 
        name: Ansible 
        duration: 10 hr 
        trainer: joindevops
    ansible.builtin.debug:
      msg: "course info {{ course | dict2items }}"