---
- name:
  hosts: local
  connection: local
  tasks: 
  - name: redirect the output using shell command
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result
  - name: print the outcome
    ansible.builtin.debug:
    msg: "{{ command_result }}"
  