---
- name: Install Nginx and Run a service
  hosts: frontend,database
  become: true
  tasks:
    - name: Check if host is reachable
      ansible.builtin.ping: 
      ignore_unreachable: true
      register: host_status
      
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true