- name: packages playbook
  hosts: frontend
  become: yes 
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - "nginx"
      - "httpd"
      - "mysql"
      - "php"